version: "3"

services:
  database:
    image: postgres:15
    expose:
      - 5432
    volumes:
      - database:/var/lib/postgresql/data/
    env_file:
      - backend/.env
    restart: always
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    command: gunicorn --access-logfile /var/log/gunicorn/access.log --error-logfile /var/log/gunicorn/error.log --bind 0.0.0.0:8000 -w 2 rnd_hack.wsgi
    depends_on:
      - database
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - backend/.env
    volumes:
      - /www/static:/backend/static_root
      - /www/media:/backend/media_root
      - /var/log/gunicorn:/var/log/gunicorn
#  frontend:
#    build:
#      context: ./frontend
#      dockerfile: ./Dockerfile
#    command: yarn start
#    ports:
#      - "3000:3000"
#    env_file:
#      - frontend/.env
#    restart: always


volumes:
  database:
