# Generated by Django 5.1.2 on 2024-10-26 21:12

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_prize'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': 'Достижение', 'verbose_name_plural': 'Достижения'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Челлендж', 'verbose_name_plural': 'Челленджи'},
        ),
        migrations.AlterModelOptions(
            name='imageswork',
            options={'verbose_name': 'Картинка работы', 'verbose_name_plural': 'Картинки работ'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'verbose_name': 'Результат', 'verbose_name_plural': 'Результаты'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': 'Работа', 'verbose_name_plural': 'Работы'},
        ),
        migrations.AddField(
            model_name='work',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='work',
            name='url_message_video',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='work',
            name='url_video',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение достижения', null=True, upload_to='achievement_images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(blank=True, help_text='Введите название достижения', max_length=50, null=True, verbose_name='Название достижения'),
        ),
        migrations.AlterField(
            model_name='event',
            name='achievement_member',
            field=models.ForeignKey(blank=True, help_text='Выберите достижение для участника', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_achiev_member', to='events.achievement', verbose_name='Достижение участника'),
        ),
        migrations.AlterField(
            model_name='event',
            name='achievement_winner',
            field=models.ForeignKey(blank=True, help_text='Выберите достижение для победителя', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_achiev_winner', to='events.achievement', verbose_name='Достижение победителя'),
        ),
        migrations.AlterField(
            model_name='event',
            name='count_photo',
            field=models.IntegerField(blank=True, help_text='Введите количество фотографий', null=True, verbose_name='Количество фотографий'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_date',
            field=models.DateField(auto_now_add=True, help_text='Дата создания события', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='event',
            name='criteries',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, help_text='Введите критерии', size=None, verbose_name='Критерии'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, help_text='Введите описание события', max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, help_text='Дата окончания события', null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='event',
            name='for_whom',
            field=models.IntegerField(blank=True, choices=[(1, 'Для себя'), (2, 'Для всех')], help_text='Выберите, для кого это событие', null=True, verbose_name='Для кого'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение события', null=True, upload_to='event_images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_finished',
            field=models.BooleanField(default=False, help_text='Укажите, завершено ли событие', verbose_name='Завершено'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_video',
            field=models.BooleanField(blank=True, help_text='Укажите, можно ли видео', null=True, verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_members',
            field=models.PositiveIntegerField(blank=True, help_text='Введите максимальное количество участников', null=True, verbose_name='Максимальное количество участников'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(blank=True, help_text='Введите название события', max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='event',
            name='prize',
            field=models.CharField(blank=True, help_text='Введите приз', max_length=100, null=True, verbose_name='Приз'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, help_text='Введите теги события', size=None, verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='imageswork',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение работы', null=True, upload_to='images_work', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='imageswork',
            name='work',
            field=models.ForeignKey(blank=True, help_text='Выберите работу', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='images_work', to='events.work', verbose_name='Работа'),
        ),
        migrations.AlterField(
            model_name='member',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Выберите событие', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='member', to='events.event', verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='member',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата присоединения участника', verbose_name='Дата присоединения'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Выберите пользователя', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='member', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='member',
            name='winner',
            field=models.BooleanField(default=False, help_text='Укажите, является ли участник победителем', verbose_name='Победитель'),
        ),
        migrations.AlterField(
            model_name='result',
            name='reviewer',
            field=models.ForeignKey(blank=True, help_text='Выберите оценивающего', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='result', to='events.member', verbose_name='Оценивающий'),
        ),
        migrations.AlterField(
            model_name='result',
            name='score',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5000), blank=True, help_text='Введите оценку', null=True, size=None, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='result',
            name='work',
            field=models.ForeignKey(blank=True, help_text='Выберите работу', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='result', to='events.work', verbose_name='Работа'),
        ),
        migrations.AlterField(
            model_name='work',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Выберите событие', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work', to='events.event', verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='work',
            name='member',
            field=models.ForeignKey(blank=True, help_text='Выберите участника', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work', to='events.member', verbose_name='Участник'),
        ),
    ]
